### ISSUE TITLE
Strategy for Process.Start and Impersonation

### ISSUE THREAD

**Issue by SearchForTheCode** [mattjohnsonpint/SimpleImpersonation#31]
Hello :)

I am trying to start a process with different rights from the inside of an windows service.

If i impersonate like this:

```csharp
Impersonation.RunAsUser(credentials, LogonType.Interactive, () => {
                      ProcessStartInfo info = new ProcessStartInfo(cmd_name, parameters);

                    info.UseShellExecute = false;
                    info.CreateNoWindow = true;
                    info.RedirectStandardOutput = true;
                    console.StartInfo = info;
                    console.Start();

                    message = console.StandardOutput.ReadToEnd();
                    });
```
the process will still run as local system. If i set the Credentials also in the ProcessStartInfo Class, i get an Access Denied. 

Currently i am using an implementation of the native call "CreateProcessAsUserW" but i was looking for an working solution with the Process Class of .NET 

Thank you :)

**Comment by mj1856** [comment]
I did some research on this, and I believe that the `ProcessStartInfo` approach will not work in any case - regardless of the execution context - because you are running inside a Windows Service.   All docs and blogs point at `CreateProcessAsUser`, so I would continue that approach.

I may consider adding another method to this library in the future, such as `Impersonation.StartProcessAsUser` which would make the appropriate calls (either through `ProcessStartInfo` or `CreateProcessAsUser` depending on environment).  I'll leave this issue open to remind me.

**Comment by SearchForTheCode** [comment]
Thank you for your fast answer :) That would be a great addition to your library and make it even more powerful! 

Just as an addition as i also ran in those issues.. Simply starting the process over the CreateProcessAsUser method is not that hard, but mostly if users start processes they also want to access stdin/stdout and react to it. This is a little bit more difficult, because you need to create pipes.

I dont know if you want to handle that too, but just as feedback, that in this case, stdin/stdout handling is a often needed use case :)

**Comment by mattjohnsonpint** [comment]
Closing, as I don't plan to add this.  Thanks.

**Comment by giuliohome** [comment]
@mattjohnsonpint 
Thank you for sharing this library. I'm going to use it in production and I've tested that it is working in my scenario

```csharp
Impersonation.RunAsUser(credentials, LogonType.Interactive, () =>
{
    System.IO.File.Copy(fileFrom, fileTo);
});
```

where it is important that I use `LogonType.Interactive` to be enabled.
Initially I tried with a more generic approach by running a batch

```csharp
public static void RunBatch()
{
    Process p = new Process();
    p.StartInfo.UseShellExecute = true; // or false, as it is easier...  I can avoid redirecting I/O
    p.StartInfo.FileName = "move.bat";
    p.StartInfo.Arguments = "file_from file_to";
    p.Start();
    p.WaitForExit();
}
```

and just for my complete reference I'd love to better understand why the latter is not working: you mentioned docs and blogs but can you share a reference? For example in the doc for [LogonUserA function (winbase.h)](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-logonusera) I read

> You can then use this token handle to impersonate the specified user or, in most cases, to create a process that runs in the context of the specified user.

so I'm unclear which is the reason why it doesn't work in this implementation?

Furthermore in my case, I can avoid redirecting I/O if that's the main issue and I can set `UseShellExecute` to true or false as it easier.

**Comment by giuliohome** [comment]
Wait a moment: can I directly call Process Start [with username and password](https://stackoverflow.com/a/59445723/11323942)?

Let me try...

**Comment by giuliohome** [comment]
But Process.Start does not work from a Task Sheduler. That is an example where SimpleImpersonation is needed. So thank you for your repository!
