### ISSUE TITLE
Strong name the library

### ISSUE THREAD

**Issue by mattjohnsonpint** [mattjohnsonpint/SimpleImpersonation#39]
The guidance from the .NET team has changed, and is now clear that OSS libraries *should* be strong named.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

This will be a breaking change
https://haacked.com/archive/2012/02/16/changing-a-strong-name-is-a-major-breaking-change.aspx/

Addresses previous requests: #1, #23, and #25

**Comment by ryancdotnet** [comment]
Greetings Matt! First off, huge respect for this library. We use it extensively in our platform, as it just makes life easier with the way .NET and Windows implement impersonation. Kudos!

I'd like to put my vote in on this issue, as we are now running into issues when attempting to share libraries that leverage SimpleImpersonation with other applications that require a strong named assembly chain.

**Comment by ryancdotnet** [comment]
I've submitted a PR for this issue. https://github.com/mattjohnsonpint/SimpleImpersonation/pull/65

**Comment by mattjohnsonpint** [comment]
Done, as of version 4.0.0.  Thanks.
