### ISSUE TITLE
Connecting to remote network shares

### ISSUE THREAD

**Issue by robertdunaway** [mattjohnsonpint/SimpleImpersonation#51]
I would like to use Impersonation.RunAsUser but I'm not sure how to direct the code to the domain unless it's by name. Should I be able to use IP address like below?  FYI I'm not really connecting to 192.168.1.1  that's just a filler.

You'll notice the commented out code.  My ultimate goal is to create a link to a network share so that I don't have to keep all our files on the www server.

Do you have any thoughts on the best way to achieve this? 

           var credentials = new UserCredentials("192.168.1.1", "user", "password");
            Impersonation.RunAsUser(credentials, LogonType.Network, () =>
           {
               //app.UseStaticFiles(new StaticFileOptions
               //{
               //    FileProvider = new PhysicalFileProvider(@"\\192.168.1.1\Images"),
               //    RequestPath = "/images",

               //});
           });

**Comment by shabshekan** [comment]
Have you found any solution?
I have same problem.

**Comment by shabshekan** [comment]
For me, this works. just need to change LogonType to NewCredentials

var credentials = new UserCredentials("192.168.1.56", "myUsername", "pass");   
                Impersonation.RunAsUser(credentials, LogonType.NewCredentials, () =>
                {
                    string fileText = System.IO.File.ReadAllText(@"\\192.168.1.56\shared\123.txt");
                    System.IO.File.WriteAllText("downloaded.txt", fileText);
                   });

**Comment by lucioteles** [comment]
> For me, this works. just need to change LogonType to NewCredentials
> 
> var credentials = new UserCredentials("192.168.1.56", "myUsername", "pass");
> Impersonation.RunAsUser(credentials, LogonType.NewCredentials, () =>
> {
> string fileText = System.IO.File.ReadAllText(@"\192.168.1.56\shared\123.txt");
> System.IO.File.WriteAllText("downloaded.txt", fileText);
> });

But doing this way, (using LogonType.NewCredentials) we're asked to inform the password...
In my case, I'm trying to impersonate an account to access shared folder on other computer to copy some files silently from times to times

Any idea?

**Comment by mj1856** [comment]
You should be able to pass `"."` for the domain if you intend the local host.

**Comment by mj1856** [comment]
... or prefixing the user with `.\` as per https://github.com/mj1856/SimpleImpersonation/issues/41#issuecomment-502187927
