### ISSUE TITLE
verify the runasuser

### ISSUE THREAD

**Issue by dchillman123** [mattjohnsonpint/SimpleImpersonation#54]
I am using this to write files to a network file share inside a .net core 3.1 web application (with logontype.newcredential).  Files do get written to the file server, and the owner of the files matches the impersonated user.  However if I get the value of the Windows.Identity.GetCurrent().Name inside the RunAsUser block, it returns the user who is running the application.  My head is swimming with all the documents I have read about impersonating users, so I am not sure if this is the expected result, or if I am not really impersonating the user correctly (to me the correct document owner implies that I am, but the GetCurrent().Name implies that I am not).  Any pointers to explain this would be appreciated.

**Comment by Ryan2065** [comment]
Hey, I realize this is an old question but thought I might be able to shine some light on this.

There's a specific type of impersonation that only uses impersonation when hitting the network. All local resources (like environment variables, and local file access) is done through the application's user, but anything done through the network uses the impersonated credentials. It's the equivalent of using the Windows command line utility runas.exe with the /netonly switch.

It sounds like that's what you are doing, which is fine if you don't need to use the credential locally. It's a standard Windows thing that's worked for decades.
