### ISSUE TITLE
Weird URL added to unc file path

### ISSUE THREAD

**Issue by LR4Discovery** [mattjohnsonpint/SimpleImpersonation#59]
Hello,

We are using this library to download a file from a web API and save a file in a network location 
It works fine when we test, using postman, on a development machine, but when we run the code in Azure PaaS Application Service Environment it adds a weird path in front of legitimate path "D:\ere\erre \\[server name]\folder\file.pdf" 
Any idea why it is doing it ? 

Thank you

**Comment by mattjohnsonpint** [comment]
No idea.  Sorry.   That's a bit out of scope for this library.

**Comment by LR4Discovery** [comment]
why out of scope, because i am running it from Azure PaaS?

**Comment by mattjohnsonpint** [comment]
This library doesn't do any file I/O operations itself.  The only thing it does is provide a managed wrapper for the `LogonUser` Win32 API to get a token handle for a specific username and password and then passes that handle to the `WindowsIdentity.Impoeronate` or `WindowsIdentity.RunImpersonated`  .NET methods.

How file I/O works within any given environment, whether single PC, local workgroup, homegroup, domain, cloud PaaS, VM, etc. is not part of this library, but part of other code your application might be calling.

Even if for some reason file I/O operations are manipulating the path when running under impersonation within some environment, that's an issue with that environment - not this library.

**Comment by LR4Discovery** [comment]
That makes sense. Thank you for the explanation

**Comment by mattjohnsonpint** [comment]
No problem, and Good luck!
