### ISSUE TITLE
Connecting over VPN

### ISSUE THREAD

**Issue by EwanScott** [mattjohnsonpint/SimpleImpersonation#64]
Does not work if you are connecting to a Domain Resource from an untrusted device, using a web app that detects user needs to add domain credentials via Browser. Dispite these being captured in the form of a Windows Identity

**Comment by mattjohnsonpint** [comment]
Hi. Per the readme for this project:

> It achives this using the [LogonUser](http://msdn.microsoft.com/en-us/library/windows/desktop/aa378184.aspx) Windows API, and thus can only provide the functionality provided by that API.

Any issue you may have with how `LogonUser` works, is outside the scope of this library.  Thanks.
