### ISSUE TITLE
How to impersonate multiple user when copying file between network drives

### ISSUE THREAD

**Issue by patricktimessupermarket** [mattjohnsonpint/SimpleImpersonation#67]
I'm having trouble copying files from one remote drive to another since I only know how to log in to one drive at a time.  Any solution to this?

```
Impersonation.RunAsUser(new UserCredentials(@"111.11.11.11", @"usern", "pw"), LogonType.NewCredentials, () =>
{

    DirectoryInfo srcEplumDQ = new DirectoryInfo(@"\\111.11.11.11");
    DirectoryInfo desEplumDQ = new DirectoryInfo(@"\\111.11.11.12"); // not logged in here

    //Move the files

});
```

**Comment by mattjohnsonpint** [comment]
As of version 4.0.0, this library simply exposes a `SafeAccessTokenHandle` that can be used with `WindowsIdentity.RunImpersonated` and similar methods.  Thus, any further discussion about what works within such impersonated code, including impersonating more than one user at a time, is better served at https://github.com/dotnet/runtime/issues.  Thanks.
