### ISSUE TITLE
Update package in NuGet

### ISSUE THREAD

**Issue by nathanpovo** [mattjohnsonpint/SimpleImpersonation#70]
The last time the [package in NuGet](https://www.nuget.org/packages/SimpleImpersonation/) was updated was more than 3 years ago. During that time there have been a number of commits to the repository.

Could you please update the package in NuGet? It would be much easier than having to maintain the repository locally.

**Comment by mattjohnsonpint** [comment]
Done.  Version 4.0.0 has been published.  Please see readme for critical breaking changes.
