### ISSUE TITLE
.NET Standard 2.0 target is not fully compatible with .NET Framework 4.6.1

### ISSUE THREAD

**Issue by OronDF343** [mattjohnsonpint/SimpleImpersonation#77]
Hi,

Installing a package with `netstandard2.0` target into a project targeting `net461` is problematic, as it adds many extra DLLs to the output. The earliest version that does not have this problem is `net471` (or in some cases even `net472`). See dotnet/standard#545 for more info.

Please add a `net461` target. Otherwise, please consider dropping official support for .NET Framework <4.7.2 (update the documentation).

Recommendation from Microsoft: (from [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting))

> CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
>
>    Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

**Comment by mattjohnsonpint** [comment]
Fixed in 4.1.0.  Thanks.
